/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assembler;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author trevo
 */
public class AssemblerGUI extends javax.swing.JFrame {

    /**
     * Creates new form AssemblerGUI
     */
    public AssemblerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopLeftBar1 = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        Sidepane = new javax.swing.JPanel();
        TopLeftBar = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        AssemblerSeparator = new javax.swing.JSeparator();
        AboutButton = new javax.swing.JPanel();
        AboutIcon = new javax.swing.JLabel();
        AboutText = new javax.swing.JLabel();
        FilenameSecton = new javax.swing.JPanel();
        FileIcon2 = new javax.swing.JLabel();
        FilenameField = new javax.swing.JTextField();
        LoadFileButton = new javax.swing.JPanel();
        FileIcon = new javax.swing.JLabel();
        FileText = new javax.swing.JLabel();
        AssembleButton = new javax.swing.JPanel();
        AssembleIcon = new javax.swing.JLabel();
        AssembleText = new javax.swing.JLabel();
        ExitButton = new javax.swing.JPanel();
        ExitIcon = new javax.swing.JLabel();
        ExitText = new javax.swing.JLabel();
        ErrorMessageBox = new javax.swing.JPanel();
        ErrorIcon = new javax.swing.JLabel();
        ErrorMessage = new javax.swing.JLabel();
        ChooseFileButton = new javax.swing.JPanel();
        FileIcon3 = new javax.swing.JLabel();
        FileText2 = new javax.swing.JLabel();
        Mainpane = new javax.swing.JPanel();
        TopPane = new javax.swing.JPanel();
        LoadFileLabel = new javax.swing.JLabel();
        LoadedFile = new javax.swing.JSeparator();
        AssembledFileLabel = new javax.swing.JLabel();
        AssembledFile = new javax.swing.JSeparator();
        PointersLabel = new javax.swing.JLabel();
        PointersSeparator = new javax.swing.JSeparator();
        TopRightBar = new javax.swing.JPanel();
        XButton = new javax.swing.JLabel();
        Loaded = new javax.swing.JScrollPane();
        LoadedFileTextArea = new javax.swing.JTextArea();
        Assembled = new javax.swing.JScrollPane();
        AssembledFileTextArea = new javax.swing.JTextArea();
        Pointers = new javax.swing.JScrollPane();
        PointersTextArea = new javax.swing.JTextArea();

        TopLeftBar1.setBackground(new java.awt.Color(82, 21, 21));
        TopLeftBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopLeftBar1MouseDragged(evt);
            }
        });
        TopLeftBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TopLeftBar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TopLeftBar1Layout = new javax.swing.GroupLayout(TopLeftBar1);
        TopLeftBar1.setLayout(TopLeftBar1Layout);
        TopLeftBar1Layout.setHorizontalGroup(
            TopLeftBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        TopLeftBar1Layout.setVerticalGroup(
            TopLeftBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assembler");
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(1250, 650));
        setMinimumSize(new java.awt.Dimension(1250, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1250, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Sidepane.setBackground(new java.awt.Color(82, 21, 21));

        TopLeftBar.setBackground(new java.awt.Color(82, 21, 21));
        TopLeftBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopLeftBarMouseDragged(evt);
            }
        });
        TopLeftBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TopLeftBarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TopLeftBarLayout = new javax.swing.GroupLayout(TopLeftBar);
        TopLeftBar.setLayout(TopLeftBarLayout);
        TopLeftBarLayout.setHorizontalGroup(
            TopLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        TopLeftBarLayout.setVerticalGroup(
            TopLeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(204, 204, 204));
        Title.setText("Assembler");

        AboutButton.setBackground(new java.awt.Color(162, 105, 105));
        AboutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AboutButton.setFocusCycleRoot(true);
        AboutButton.setNextFocusableComponent(FilenameField);
        AboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutButtonMouseExited(evt);
            }
        });

        AboutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assembler.images/HelpIcon25.png"))); // NOI18N

        AboutText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AboutText.setForeground(new java.awt.Color(204, 204, 204));
        AboutText.setText("About");

        javax.swing.GroupLayout AboutButtonLayout = new javax.swing.GroupLayout(AboutButton);
        AboutButton.setLayout(AboutButtonLayout);
        AboutButtonLayout.setHorizontalGroup(
            AboutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AboutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AboutText, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AboutButtonLayout.setVerticalGroup(
            AboutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AboutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AboutText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AboutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        FilenameSecton.setBackground(new java.awt.Color(123, 70, 70));
        FilenameSecton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FilenameSecton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilenameSectonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FilenameSectonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FilenameSectonMouseExited(evt);
            }
        });

        FileIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FileIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assembler.images/OFileIcon25.png"))); // NOI18N

        FilenameField.setBackground(new java.awt.Color(82, 21, 21));
        FilenameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FilenameField.setForeground(new java.awt.Color(204, 204, 204));
        FilenameField.setNextFocusableComponent(LoadFileButton);
        FilenameField.setSelectedTextColor(new java.awt.Color(39, 39, 39));
        FilenameField.setSelectionColor(new java.awt.Color(46, 47, 48));
        FilenameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilenameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FilenameSectonLayout = new javax.swing.GroupLayout(FilenameSecton);
        FilenameSecton.setLayout(FilenameSectonLayout);
        FilenameSectonLayout.setHorizontalGroup(
            FilenameSectonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilenameSectonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FilenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FilenameSectonLayout.setVerticalGroup(
            FilenameSectonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilenameSectonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FilenameSectonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FileIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(FilenameField))
                .addContainerGap())
        );

        LoadFileButton.setBackground(new java.awt.Color(123, 70, 70));
        LoadFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoadFileButton.setNextFocusableComponent(AssembleButton);
        LoadFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoadFileButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoadFileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoadFileButtonMouseExited(evt);
            }
        });

        FileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assembler.images/LoadIcon25.png"))); // NOI18N

        FileText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FileText.setForeground(new java.awt.Color(204, 204, 204));
        FileText.setText("Load File");

        javax.swing.GroupLayout LoadFileButtonLayout = new javax.swing.GroupLayout(LoadFileButton);
        LoadFileButton.setLayout(LoadFileButtonLayout);
        LoadFileButtonLayout.setHorizontalGroup(
            LoadFileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoadFileButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FileText, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LoadFileButtonLayout.setVerticalGroup(
            LoadFileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoadFileButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoadFileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FileText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        AssembleButton.setBackground(new java.awt.Color(108, 42, 42));
        AssembleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AssembleButton.setName(""); // NOI18N
        AssembleButton.setNextFocusableComponent(ExitButton);
        AssembleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssembleButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AssembleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AssembleButtonMouseExited(evt);
            }
        });

        AssembleIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AssembleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assembler.images/GearIcon25.png"))); // NOI18N

        AssembleText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AssembleText.setForeground(new java.awt.Color(204, 204, 204));
        AssembleText.setText("Assemble Program");

        javax.swing.GroupLayout AssembleButtonLayout = new javax.swing.GroupLayout(AssembleButton);
        AssembleButton.setLayout(AssembleButtonLayout);
        AssembleButtonLayout.setHorizontalGroup(
            AssembleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssembleButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AssembleIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AssembleText, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AssembleButtonLayout.setVerticalGroup(
            AssembleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssembleButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AssembleButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AssembleText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AssembleIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        ExitButton.setBackground(new java.awt.Color(108, 42, 42));
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitButton.setNextFocusableComponent(LoadedFileTextArea);
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitButtonMouseExited(evt);
            }
        });

        ExitIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assembler.images/ExitIcon25.png"))); // NOI18N

        ExitText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitText.setForeground(new java.awt.Color(204, 204, 204));
        ExitText.setText("Exit Application");

        javax.swing.GroupLayout ExitButtonLayout = new javax.swing.GroupLayout(ExitButton);
        ExitButton.setLayout(ExitButtonLayout);
        ExitButtonLayout.setHorizontalGroup(
            ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExitText, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ExitButtonLayout.setVerticalGroup(
            ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        ErrorMessageBox.setBackground(new java.awt.Color(61, 0, 0));
        ErrorMessageBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ErrorMessageBoxMouseClicked(evt);
            }
        });

        ErrorIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assembler.images/ErrorIcon25.png"))); // NOI18N

        ErrorMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ErrorMessage.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout ErrorMessageBoxLayout = new javax.swing.GroupLayout(ErrorMessageBox);
        ErrorMessageBox.setLayout(ErrorMessageBoxLayout);
        ErrorMessageBoxLayout.setHorizontalGroup(
            ErrorMessageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorMessageBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ErrorIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ErrorMessageBoxLayout.setVerticalGroup(
            ErrorMessageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErrorMessageBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ErrorMessageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ErrorIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        ChooseFileButton.setBackground(new java.awt.Color(123, 70, 70));
        ChooseFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChooseFileButton.setFocusCycleRoot(true);
        ChooseFileButton.setNextFocusableComponent(FilenameField);
        ChooseFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChooseFileButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChooseFileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChooseFileButtonMouseExited(evt);
            }
        });

        FileIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FileIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assembler.images/FileIcon25.png"))); // NOI18N

        FileText2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FileText2.setForeground(new java.awt.Color(204, 204, 204));
        FileText2.setText("Choose File");

        javax.swing.GroupLayout ChooseFileButtonLayout = new javax.swing.GroupLayout(ChooseFileButton);
        ChooseFileButton.setLayout(ChooseFileButtonLayout);
        ChooseFileButtonLayout.setHorizontalGroup(
            ChooseFileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChooseFileButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FileText2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ChooseFileButtonLayout.setVerticalGroup(
            ChooseFileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChooseFileButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChooseFileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FileText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FileIcon3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout SidepaneLayout = new javax.swing.GroupLayout(Sidepane);
        Sidepane.setLayout(SidepaneLayout);
        SidepaneLayout.setHorizontalGroup(
            SidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopLeftBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SidepaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(SidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(AssemblerSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidepaneLayout.createSequentialGroup()
                .addGroup(SidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AboutButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(FilenameSecton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoadFileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(AssembleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(ErrorMessageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(ChooseFileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, Short.MAX_VALUE))
                .addContainerGap())
        );
        SidepaneLayout.setVerticalGroup(
            SidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidepaneLayout.createSequentialGroup()
                .addComponent(TopLeftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssemblerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FilenameSecton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssembleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorMessageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        Mainpane.setBackground(new java.awt.Color(39, 39, 39));
        Mainpane.setMinimumSize(new java.awt.Dimension(1280, 600));
        Mainpane.setPreferredSize(new java.awt.Dimension(865, 500));

        TopPane.setBackground(new java.awt.Color(82, 21, 21));

        LoadFileLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoadFileLabel.setForeground(new java.awt.Color(204, 204, 204));
        LoadFileLabel.setText("Loaded File");

        AssembledFileLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AssembledFileLabel.setForeground(new java.awt.Color(204, 204, 204));
        AssembledFileLabel.setText("Assembled File");

        PointersLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PointersLabel.setForeground(new java.awt.Color(204, 204, 204));
        PointersLabel.setText("Symbol Table");

        javax.swing.GroupLayout TopPaneLayout = new javax.swing.GroupLayout(TopPane);
        TopPane.setLayout(TopPaneLayout);
        TopPaneLayout.setHorizontalGroup(
            TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoadedFile)
                    .addComponent(LoadFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AssembledFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(AssembledFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PointersSeparator)
                    .addComponent(PointersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        TopPaneLayout.setVerticalGroup(
            TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoadFileLabel)
                    .addComponent(AssembledFileLabel)
                    .addComponent(PointersLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoadedFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssembledFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PointersSeparator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TopRightBar.setBackground(new java.awt.Color(39, 39, 39));
        TopRightBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopRightBarMouseDragged(evt);
            }
        });
        TopRightBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TopRightBarMouseClicked(evt);
            }
        });

        XButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        XButton.setForeground(new java.awt.Color(204, 204, 204));
        XButton.setText("X");
        XButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TopRightBarLayout = new javax.swing.GroupLayout(TopRightBar);
        TopRightBar.setLayout(TopRightBarLayout);
        TopRightBarLayout.setHorizontalGroup(
            TopRightBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopRightBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(XButton)
                .addGap(19, 19, 19))
        );
        TopRightBarLayout.setVerticalGroup(
            TopRightBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopRightBarLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(XButton))
        );

        LoadedFileTextArea.setBackground(new java.awt.Color(46, 47, 48));
        LoadedFileTextArea.setColumns(20);
        LoadedFileTextArea.setForeground(new java.awt.Color(204, 204, 204));
        LoadedFileTextArea.setRows(5);
        LoadedFileTextArea.setMinimumSize(new java.awt.Dimension(500, 300));
        LoadedFileTextArea.setNextFocusableComponent(AssembledFileTextArea);
        LoadedFileTextArea.setSelectionColor(new java.awt.Color(108, 42, 42));
        Loaded.setViewportView(LoadedFileTextArea);

        AssembledFileTextArea.setBackground(new java.awt.Color(46, 47, 48));
        AssembledFileTextArea.setColumns(20);
        AssembledFileTextArea.setForeground(new java.awt.Color(204, 204, 204));
        AssembledFileTextArea.setRows(5);
        AssembledFileTextArea.setMinimumSize(new java.awt.Dimension(500, 300));
        AssembledFileTextArea.setNextFocusableComponent(PointersTextArea);
        AssembledFileTextArea.setSelectionColor(new java.awt.Color(108, 42, 42));
        Assembled.setViewportView(AssembledFileTextArea);

        PointersTextArea.setBackground(new java.awt.Color(46, 47, 48));
        PointersTextArea.setColumns(20);
        PointersTextArea.setForeground(new java.awt.Color(204, 204, 204));
        PointersTextArea.setRows(5);
        PointersTextArea.setMinimumSize(new java.awt.Dimension(500, 300));
        PointersTextArea.setNextFocusableComponent(ExitButton);
        PointersTextArea.setSelectionColor(new java.awt.Color(108, 42, 42));
        Pointers.setViewportView(PointersTextArea);

        javax.swing.GroupLayout MainpaneLayout = new javax.swing.GroupLayout(Mainpane);
        Mainpane.setLayout(MainpaneLayout);
        MainpaneLayout.setHorizontalGroup(
            MainpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainpaneLayout.createSequentialGroup()
                .addGroup(MainpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TopRightBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MainpaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Loaded, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Assembled, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pointers, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainpaneLayout.setVerticalGroup(
            MainpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainpaneLayout.createSequentialGroup()
                .addComponent(TopRightBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Loaded, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Assembled, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pointers, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(0, 354, Short.MAX_VALUE)
                .addComponent(Mainpane, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addComponent(Sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 899, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mainpane, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Sidepane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Load file into text area.
     */
    private void LoadFile(){
        try {
            // Clear Assembled File and Pointers text areas
            AssembledFileTextArea.setText("");
            PointersTextArea.setText("");
            // Read the file into the textarea
            LoadedFileTextArea.setText(Assembler.ReadFile(FilenameField.getText()));
            // Clear any error messages
            ErrorMessageBox.setVisible(false);
        } catch (AssemblerException e) {
            ErrorMessageBox.setVisible(true);
            ErrorMessage.setText(e.getMessage());
        }
    }
    /**
     * Assemble Program and set text areas
     */
    private void AssembleProgram(){
        try {
            // Assemble Program
            Assembler.Assemble(LoadedFileTextArea.getText());
            // Set Assembled File and Pointers Text Areas
            AssembledFileTextArea.setText(Assembler.getCode());
            PointersTextArea.setText(Assembler.getPointers());
            // Save files
            Assembler.saveFiles();
            // Hide any error messages
            ErrorMessageBox.setVisible(false);
        } catch (AssemblerException e){
            ErrorMessageBox.setVisible(true);
            ErrorMessage.setText(e.getMessage());
        }
    }
    /**
     * Choose File with file chooser, load file, and assemble file
     */
    private void ChooseFile(){
        // Get current directory
        String currentDirectory = System.getProperty("user.dir");
        // Open file chooser to current directory
        JFileChooser chooser = new JFileChooser(currentDirectory);
        chooser.showOpenDialog(null);
        // Get file selected
        File f = chooser.getSelectedFile();
        // Set filename field with selected file
        FilenameField.setText(f.getAbsolutePath());
        // Load the file
        LoadFile();
        // Assemble the file
        AssembleProgram();
    }
    
    private void LoadFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadFileButtonMouseClicked
        LoadFile();
    }//GEN-LAST:event_LoadFileButtonMouseClicked
    
    private void AssembleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssembleButtonMouseClicked
        AssembleProgram();
    }//GEN-LAST:event_AssembleButtonMouseClicked

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void FilenameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilenameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilenameFieldActionPerformed

    private void XButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XButtonMouseClicked

    // For mouse listener
    private static int posX=0;
    private static int posY=0;
    
    private void TopLeftBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopLeftBarMouseClicked
        posX=evt.getX();
        posY=evt.getY();
    }//GEN-LAST:event_TopLeftBarMouseClicked

    private void TopLeftBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopLeftBarMouseDragged
        setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_TopLeftBarMouseDragged

    private void TopRightBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopRightBarMouseDragged
        setLocation (evt.getXOnScreen()-posX,evt.getYOnScreen()-posY);
    }//GEN-LAST:event_TopRightBarMouseDragged

    private void TopRightBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopRightBarMouseClicked
        posX=evt.getX();
        posY=evt.getY();
    }//GEN-LAST:event_TopRightBarMouseClicked

    Color PinkRed = new Color(162,105,105);
    Color LightRed = new Color(123,70,70);
    Color MediumRed = new Color(108,42,42);
    Color DarkRed = new Color(82,21,21);
    Color ErrorRed = new Color(61,0,0);
    Color Hover = new Color(61,0,0);
    // Light Grey: 46,47,48
    // Dark Grey: 39,39,39
    
    private void FilenameSectonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilenameSectonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FilenameSectonMouseClicked

    private void TopLeftBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopLeftBar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TopLeftBar1MouseClicked

    private void TopLeftBar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopLeftBar1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_TopLeftBar1MouseDragged

    private void ErrorMessageBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ErrorMessageBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorMessageBoxMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ErrorMessageBox.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void FilenameSectonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilenameSectonMouseEntered
        FilenameSecton.setBackground(Hover);
    }//GEN-LAST:event_FilenameSectonMouseEntered

    private void FilenameSectonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilenameSectonMouseExited
        FilenameSecton.setBackground(LightRed);
    }//GEN-LAST:event_FilenameSectonMouseExited

    private void LoadFileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadFileButtonMouseEntered
        LoadFileButton.setBackground(Hover);
    }//GEN-LAST:event_LoadFileButtonMouseEntered

    private void LoadFileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadFileButtonMouseExited
        LoadFileButton.setBackground(LightRed);
    }//GEN-LAST:event_LoadFileButtonMouseExited

    private void AssembleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssembleButtonMouseEntered
        AssembleButton.setBackground(Hover);
    }//GEN-LAST:event_AssembleButtonMouseEntered

    private void AssembleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssembleButtonMouseExited
        AssembleButton.setBackground(MediumRed);
    }//GEN-LAST:event_AssembleButtonMouseExited

    private void ExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseEntered
        ExitButton.setBackground(Hover);
    }//GEN-LAST:event_ExitButtonMouseEntered

    private void ExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseExited
       ExitButton.setBackground(MediumRed);
    }//GEN-LAST:event_ExitButtonMouseExited

    private void ChooseFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseFileButtonMouseClicked
        ChooseFile();
    }//GEN-LAST:event_ChooseFileButtonMouseClicked

    private void ChooseFileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseFileButtonMouseEntered
        ChooseFileButton.setBackground(Hover);
    }//GEN-LAST:event_ChooseFileButtonMouseEntered

    private void ChooseFileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseFileButtonMouseExited
        ChooseFileButton.setBackground(LightRed);
    }//GEN-LAST:event_ChooseFileButtonMouseExited

    private void AboutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutButtonMouseExited
        AboutButton.setBackground(PinkRed);
    }//GEN-LAST:event_AboutButtonMouseExited

    private void AboutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutButtonMouseEntered
        AboutButton.setBackground(Hover);
    }//GEN-LAST:event_AboutButtonMouseEntered

    private void AboutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutButtonMouseClicked
        LoadedFileTextArea.setText(Assembler.about());
    }//GEN-LAST:event_AboutButtonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /** ADDED THIS ONE LINE **/
        JFrame.setDefaultLookAndFeelDecorated(false);
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssemblerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssemblerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssemblerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssemblerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssemblerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutButton;
    private javax.swing.JLabel AboutIcon;
    private javax.swing.JLabel AboutText;
    private javax.swing.JPanel AssembleButton;
    private javax.swing.JLabel AssembleIcon;
    private javax.swing.JLabel AssembleText;
    private javax.swing.JScrollPane Assembled;
    private javax.swing.JSeparator AssembledFile;
    private javax.swing.JLabel AssembledFileLabel;
    private javax.swing.JTextArea AssembledFileTextArea;
    private javax.swing.JSeparator AssemblerSeparator;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel ChooseFileButton;
    private javax.swing.JLabel ErrorIcon;
    private javax.swing.JLabel ErrorMessage;
    private javax.swing.JPanel ErrorMessageBox;
    private javax.swing.JPanel ExitButton;
    private javax.swing.JLabel ExitIcon;
    private javax.swing.JLabel ExitText;
    private javax.swing.JLabel FileIcon;
    private javax.swing.JLabel FileIcon2;
    private javax.swing.JLabel FileIcon3;
    private javax.swing.JLabel FileText;
    private javax.swing.JLabel FileText2;
    private javax.swing.JTextField FilenameField;
    private javax.swing.JPanel FilenameSecton;
    private javax.swing.JPanel LoadFileButton;
    private javax.swing.JLabel LoadFileLabel;
    private javax.swing.JScrollPane Loaded;
    private javax.swing.JSeparator LoadedFile;
    private javax.swing.JTextArea LoadedFileTextArea;
    private javax.swing.JPanel Mainpane;
    private javax.swing.JScrollPane Pointers;
    private javax.swing.JLabel PointersLabel;
    private javax.swing.JSeparator PointersSeparator;
    private javax.swing.JTextArea PointersTextArea;
    private javax.swing.JPanel Sidepane;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TopLeftBar;
    private javax.swing.JPanel TopLeftBar1;
    private javax.swing.JPanel TopPane;
    private javax.swing.JPanel TopRightBar;
    private javax.swing.JLabel XButton;
    // End of variables declaration//GEN-END:variables
}
